version: "3.8"

services:
  # 1. The Message Broker
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672" # Standard AMQP port
      - "15672:15672" # Management UI (Dashboard)
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # 2. Lobby Service (Matchmaking & Sessions)
  lobby_service:
    build: .
    command: python -m grcp_server.lobby_server
    ports:
      - "50051:50051"
    depends_on:
      rabbitmq:
        condition: service_healthy

  # 3. Action Service (Hacker & Infiltrator game actions)
  action_service:
    build: .
    command: python -m grcp_server.action_server
    ports:
      - "50052:50052"
    depends_on:
      rabbitmq:
        condition: service_healthy
