# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import heist_pb2 as heist__pb2

GRPC_GENERATED_VERSION = '1.81.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in heist_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class HeistGameStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.unlockDoor = channel.unary_unary(
                '/HeistGame/unlockDoor',
                request_serializer=heist__pb2.TargetRequest.SerializeToString,
                response_deserializer=heist__pb2.ActionResponse.FromString,
                _registered_method=True)
        self.disableCamera = channel.unary_unary(
                '/HeistGame/disableCamera',
                request_serializer=heist__pb2.TargetRequest.SerializeToString,
                response_deserializer=heist__pb2.ActionResponse.FromString,
                _registered_method=True)
        self.disableLaser = channel.unary_unary(
                '/HeistGame/disableLaser',
                request_serializer=heist__pb2.TargetRequest.SerializeToString,
                response_deserializer=heist__pb2.ActionResponse.FromString,
                _registered_method=True)
        self.grantNetworkAccess = channel.unary_unary(
                '/HeistGame/grantNetworkAccess',
                request_serializer=heist__pb2.AccessRequest.SerializeToString,
                response_deserializer=heist__pb2.ActionResponse.FromString,
                _registered_method=True)
        self.requestVote = channel.unary_unary(
                '/HeistGame/requestVote',
                request_serializer=heist__pb2.VoteRequest.SerializeToString,
                response_deserializer=heist__pb2.VoteResponse.FromString,
                _registered_method=True)


class HeistGameServicer:
    """Missing associated documentation comment in .proto file."""

    def unlockDoor(self, request, context):
        """---------------------------------------------------------
        HACKER ACTIONS (Called from Server B, executed on Server A)
        ---------------------------------------------------------
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def disableCamera(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def disableLaser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def grantNetworkAccess(self, request, context):
        """---------------------------------------------------------
        INFILTRATOR ACTIONS (Called from Server A, executed on Server B)
        ---------------------------------------------------------
        Infiltrator plugs in USB to give Hacker access to the next zone
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def requestVote(self, request, context):
        """---------------------------------------------------------
        DISTRIBUTED ALGORITHMS (The Maekawa Vault Download)
        ---------------------------------------------------------
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HeistGameServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'unlockDoor': grpc.unary_unary_rpc_method_handler(
                    servicer.unlockDoor,
                    request_deserializer=heist__pb2.TargetRequest.FromString,
                    response_serializer=heist__pb2.ActionResponse.SerializeToString,
            ),
            'disableCamera': grpc.unary_unary_rpc_method_handler(
                    servicer.disableCamera,
                    request_deserializer=heist__pb2.TargetRequest.FromString,
                    response_serializer=heist__pb2.ActionResponse.SerializeToString,
            ),
            'disableLaser': grpc.unary_unary_rpc_method_handler(
                    servicer.disableLaser,
                    request_deserializer=heist__pb2.TargetRequest.FromString,
                    response_serializer=heist__pb2.ActionResponse.SerializeToString,
            ),
            'grantNetworkAccess': grpc.unary_unary_rpc_method_handler(
                    servicer.grantNetworkAccess,
                    request_deserializer=heist__pb2.AccessRequest.FromString,
                    response_serializer=heist__pb2.ActionResponse.SerializeToString,
            ),
            'requestVote': grpc.unary_unary_rpc_method_handler(
                    servicer.requestVote,
                    request_deserializer=heist__pb2.VoteRequest.FromString,
                    response_serializer=heist__pb2.VoteResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'HeistGame', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('HeistGame', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class HeistGame:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def unlockDoor(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/HeistGame/unlockDoor',
            heist__pb2.TargetRequest.SerializeToString,
            heist__pb2.ActionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def disableCamera(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/HeistGame/disableCamera',
            heist__pb2.TargetRequest.SerializeToString,
            heist__pb2.ActionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def disableLaser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/HeistGame/disableLaser',
            heist__pb2.TargetRequest.SerializeToString,
            heist__pb2.ActionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def grantNetworkAccess(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/HeistGame/grantNetworkAccess',
            heist__pb2.AccessRequest.SerializeToString,
            heist__pb2.ActionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def requestVote(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/HeistGame/requestVote',
            heist__pb2.VoteRequest.SerializeToString,
            heist__pb2.VoteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
