# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import heist_pb2 as heist__pb2

GRPC_GENERATED_VERSION = '1.81.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in heist_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class HeistGameStub:
    """This defines the "Methods" servers can call on each other
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.unlockDoor = channel.unary_unary(
                '/HeistGame/unlockDoor',
                request_serializer=heist__pb2.DoorRequest.SerializeToString,
                response_deserializer=heist__pb2.ActionResponse.FromString,
                _registered_method=True)
        self.requestVote = channel.unary_unary(
                '/HeistGame/requestVote',
                request_serializer=heist__pb2.VoteRequest.SerializeToString,
                response_deserializer=heist__pb2.VoteResponse.FromString,
                _registered_method=True)


class HeistGameServicer:
    """This defines the "Methods" servers can call on each other
    """

    def unlockDoor(self, request, context):
        """Hacker asks Infiltrator's server to open a door
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def requestVote(self, request, context):
        """For the Maekawa Algorithm (Mutual Exclusion)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HeistGameServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'unlockDoor': grpc.unary_unary_rpc_method_handler(
                    servicer.unlockDoor,
                    request_deserializer=heist__pb2.DoorRequest.FromString,
                    response_serializer=heist__pb2.ActionResponse.SerializeToString,
            ),
            'requestVote': grpc.unary_unary_rpc_method_handler(
                    servicer.requestVote,
                    request_deserializer=heist__pb2.VoteRequest.FromString,
                    response_serializer=heist__pb2.VoteResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'HeistGame', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('HeistGame', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class HeistGame:
    """This defines the "Methods" servers can call on each other
    """

    @staticmethod
    def unlockDoor(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/HeistGame/unlockDoor',
            heist__pb2.DoorRequest.SerializeToString,
            heist__pb2.ActionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def requestVote(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/HeistGame/requestVote',
            heist__pb2.VoteRequest.SerializeToString,
            heist__pb2.VoteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
