# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: grcp_server/action.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'grcp_server/action.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18grcp_server/action.proto\x12\x06\x61\x63tion\"I\n\rTargetRequest\x12\x11\n\ttarget_id\x18\x01 \x01(\t\x12\x11\n\thacker_id\x18\x02 \x01(\t\x12\x12\n\nlobby_code\x18\x03 \x01(\t\"O\n\rAccessRequest\x12\x17\n\x0f\x61\x63\x63\x65ss_point_id\x18\x01 \x01(\t\x12\x11\n\thacker_id\x18\x02 \x01(\t\x12\x12\n\nlobby_code\x18\x03 \x01(\t\"2\n\x0e\x41\x63tionResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2\x98\x02\n\rActionService\x12=\n\nUnlockDoor\x12\x15.action.TargetRequest\x1a\x16.action.ActionResponse\"\x00\x12@\n\rDisableCamera\x12\x15.action.TargetRequest\x1a\x16.action.ActionResponse\"\x00\x12?\n\x0c\x44isableLaser\x12\x15.action.TargetRequest\x1a\x16.action.ActionResponse\"\x00\x12\x45\n\x12GrantNetworkAccess\x12\x15.action.AccessRequest\x1a\x16.action.ActionResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'grcp_server.action_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TARGETREQUEST']._serialized_start=36
  _globals['_TARGETREQUEST']._serialized_end=109
  _globals['_ACCESSREQUEST']._serialized_start=111
  _globals['_ACCESSREQUEST']._serialized_end=190
  _globals['_ACTIONRESPONSE']._serialized_start=192
  _globals['_ACTIONRESPONSE']._serialized_end=242
  _globals['_ACTIONSERVICE']._serialized_start=245
  _globals['_ACTIONSERVICE']._serialized_end=525
# @@protoc_insertion_point(module_scope)
