# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from grpc_server import action_pb2 as grcp__server_dot_action__pb2

GRPC_GENERATED_VERSION = '1.81.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in grcp_server/action_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ActionServiceStub:
    """Action Service: Handles all in-game actions for Hacker and Infiltrator roles.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.UnlockDoor = channel.unary_unary(
                '/action.ActionService/UnlockDoor',
                request_serializer=grcp__server_dot_action__pb2.TargetRequest.SerializeToString,
                response_deserializer=grcp__server_dot_action__pb2.ActionResponse.FromString,
                _registered_method=True)
        self.DisableCamera = channel.unary_unary(
                '/action.ActionService/DisableCamera',
                request_serializer=grcp__server_dot_action__pb2.TargetRequest.SerializeToString,
                response_deserializer=grcp__server_dot_action__pb2.ActionResponse.FromString,
                _registered_method=True)
        self.DisableLaser = channel.unary_unary(
                '/action.ActionService/DisableLaser',
                request_serializer=grcp__server_dot_action__pb2.TargetRequest.SerializeToString,
                response_deserializer=grcp__server_dot_action__pb2.ActionResponse.FromString,
                _registered_method=True)
        self.GrantNetworkAccess = channel.unary_unary(
                '/action.ActionService/GrantNetworkAccess',
                request_serializer=grcp__server_dot_action__pb2.AccessRequest.SerializeToString,
                response_deserializer=grcp__server_dot_action__pb2.ActionResponse.FromString,
                _registered_method=True)


class ActionServiceServicer:
    """Action Service: Handles all in-game actions for Hacker and Infiltrator roles.
    """

    def UnlockDoor(self, request, context):
        """Hacker Actions
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DisableCamera(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DisableLaser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GrantNetworkAccess(self, request, context):
        """Infiltrator Actions
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ActionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'UnlockDoor': grpc.unary_unary_rpc_method_handler(
                    servicer.UnlockDoor,
                    request_deserializer=grcp__server_dot_action__pb2.TargetRequest.FromString,
                    response_serializer=grcp__server_dot_action__pb2.ActionResponse.SerializeToString,
            ),
            'DisableCamera': grpc.unary_unary_rpc_method_handler(
                    servicer.DisableCamera,
                    request_deserializer=grcp__server_dot_action__pb2.TargetRequest.FromString,
                    response_serializer=grcp__server_dot_action__pb2.ActionResponse.SerializeToString,
            ),
            'DisableLaser': grpc.unary_unary_rpc_method_handler(
                    servicer.DisableLaser,
                    request_deserializer=grcp__server_dot_action__pb2.TargetRequest.FromString,
                    response_serializer=grcp__server_dot_action__pb2.ActionResponse.SerializeToString,
            ),
            'GrantNetworkAccess': grpc.unary_unary_rpc_method_handler(
                    servicer.GrantNetworkAccess,
                    request_deserializer=grcp__server_dot_action__pb2.AccessRequest.FromString,
                    response_serializer=grcp__server_dot_action__pb2.ActionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'action.ActionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('action.ActionService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ActionService:
    """Action Service: Handles all in-game actions for Hacker and Infiltrator roles.
    """

    @staticmethod
    def UnlockDoor(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/action.ActionService/UnlockDoor',
            grcp__server_dot_action__pb2.TargetRequest.SerializeToString,
            grcp__server_dot_action__pb2.ActionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DisableCamera(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/action.ActionService/DisableCamera',
            grcp__server_dot_action__pb2.TargetRequest.SerializeToString,
            grcp__server_dot_action__pb2.ActionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DisableLaser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/action.ActionService/DisableLaser',
            grcp__server_dot_action__pb2.TargetRequest.SerializeToString,
            grcp__server_dot_action__pb2.ActionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GrantNetworkAccess(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/action.ActionService/GrantNetworkAccess',
            grcp__server_dot_action__pb2.AccessRequest.SerializeToString,
            grcp__server_dot_action__pb2.ActionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
