# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: grcp_server/lobby.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'grcp_server/lobby.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17grcp_server/lobby.proto\x12\x05lobby\"\'\n\x12\x43reateLobbyRequest\x12\x11\n\tplayer_id\x18\x01 \x01(\t\"9\n\x10JoinLobbyRequest\x12\x12\n\nlobby_code\x18\x01 \x01(\t\x12\x11\n\tplayer_id\x18\x02 \x01(\t\"\\\n\rLobbyResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x12\n\nlobby_code\x18\x03 \x01(\t\x12\x15\n\rassigned_role\x18\x04 \x01(\t2\x8e\x01\n\x0cLobbyService\x12@\n\x0b\x43reateLobby\x12\x19.lobby.CreateLobbyRequest\x1a\x14.lobby.LobbyResponse\"\x00\x12<\n\tJoinLobby\x12\x17.lobby.JoinLobbyRequest\x1a\x14.lobby.LobbyResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'grcp_server.lobby_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CREATELOBBYREQUEST']._serialized_start=34
  _globals['_CREATELOBBYREQUEST']._serialized_end=73
  _globals['_JOINLOBBYREQUEST']._serialized_start=75
  _globals['_JOINLOBBYREQUEST']._serialized_end=132
  _globals['_LOBBYRESPONSE']._serialized_start=134
  _globals['_LOBBYRESPONSE']._serialized_end=226
  _globals['_LOBBYSERVICE']._serialized_start=229
  _globals['_LOBBYSERVICE']._serialized_end=371
# @@protoc_insertion_point(module_scope)
